from __future__ import annotations

import json
from pathlib import Path
import shutil

from building3d.artifacts import artifact_names


def package_export(config) -> Path:
    config.export_dir.mkdir(parents=True, exist_ok=True)
    names = artifact_names(config.building_id)
    manifest_src = config.processed_dir / names.manifest
    if manifest_src.exists():
        shutil.copy2(manifest_src, config.export_dir / names.manifest)
    _write_readme(config.export_dir, config)
    return config.export_dir


def _write_readme(export_dir: Path, config) -> None:
    names = artifact_names(config.building_id)
    manifest_path = export_dir / names.manifest
    room_count = "unknown"
    floor_count = "unknown"
    if manifest_path.exists():
        with manifest_path.open("r", encoding="utf-8") as handle:
            manifest = json.load(handle)
        room_count = str(len(manifest.get("rooms", [])))
        floor_count = str(len(manifest.get("floors", [])))

    readme = f"""# {config.display_name} Export

Generated by Building3D.

## Contents

- `{names.visual_glb}`: visible building model.
- `{names.nav_glb}`: simplified navigation surfaces and markers.
- `{names.manifest}`: room, floor, portal, anchor, alias, and provenance data.

## Coordinate System

- X: east/west metres from the configured origin.
- Y: generated floor height.
- Z: north/south metres from the configured origin.
- Scale: 1 unit = 1 metre.

## Summary

- Building id: `{config.building_id}`
- MapsIndoors admin id: `{config.building_admin_id}`
- Floors: {floor_count}
- Rooms: {room_count}

## Known Limitations

- Door positions are inferred, not authoritative.
- Raster floor tiles and raw MapsIndoors responses are not included.
- This package is standalone and has not been copied into UNIMATE.
"""
    (export_dir / "README.md").write_text(readme, encoding="utf-8")
